name: ci
on:
  pull_request:
  push:
    branches:
      - master
      - llvm18
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  x86_64-linux-debug:
    timeout-minutes: 420
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: sh ci/x86_64-linux-debug.sh
  x86_64-windows-debug:
    runs-on: windows-latest
    env:
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: ci/x86_64-windows-debug.ps1
